# This program says hello and asks for your name
print('Hello world!')
print('What is your name?')
name = input()
print('It is good to meet you ' + name)
print('The length of your name is:')
print(len(name))
print('What is your age?')
age = input()
print('You will be ' + str(int(age) + 5) + ' in 5 years time')
